version: "3"
services:
  someapi:
    build:
      context: ./AmsAPI
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./AmsUI
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - someapi