import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { FaIconLibrary, FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {
  faAddressBook,
  faBinoculars,
  faBooks,
  faCalculator,
  faCalculatorAlt,
  faCalendarAlt,
  faCalendarDay,
  faChartNetwork,
  faCheck,
  faCheckCircle,
  faClock,
  faCloud,
  faCog,
  faCommentsAlt,
  faCopy,
  fad,
  faDrawPolygon,
  faEdit,
  faEnvelope,
  faEye,
  faFileChartLine,
  faFileCheck,
  faFileInvoiceDollar,
  faGlobeAmericas,
  faGraduationCap,
  faHome,
  faImages,
  faKey,
  faLink,
  faList,
  faPen,
  faPlusCircle,
  faQuestionCircle,
  faSave,
  faSlidersH,
  faTags,
  faTasks,
  faThList,
  faTimesCircle,
  faTrash,
  faTruckPickup,
  faUsdCircle,
  faUserClock,
  faUserLock,
  faUsers,
  faUsersCog,
  faWarehouse,
  faWarehouseAlt,
  faSignOutAlt,
} from '@fortawesome/pro-duotone-svg-icons';
import { fal, faPlus } from '@fortawesome/pro-light-svg-icons';
import { faBars, far } from '@fortawesome/pro-regular-svg-icons';
import {
  faArrowToBottom,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faExclamationCircle,
  faHourglassEnd,
  faMinusCircle,
  faMoneyCheckAlt,
  fas,
  faSearch,
  faSpinner
} from '@fortawesome/pro-solid-svg-icons';
import { TableComponent } from './common/table.component';
import { OnDestroyComponent } from './common/on-destroy.component';

@NgModule({
  imports: [CommonModule, ReactiveFormsModule, FontAwesomeModule],
  exports: [
    CommonModule,
    ReactiveFormsModule,
    FontAwesomeModule,
  ],
  // declarations: [TableComponent, OnDestroyComponent],
})
export class CoreModule {
  constructor(private readonly library: FaIconLibrary) {
    library.addIconPacks(fad, far, fas, fal);
    library.addIcons(
      faHome,
      faUsersCog,
      faEnvelope,
      faAddressBook,
      faCalculator,
      faBooks,
      faCalculatorAlt,
      faUserClock,
      faWarehouse,
      faCalendarAlt,
      faFileInvoiceDollar,
      faBars,
      faClock,
      faCog,
      faCommentsAlt,
      faGlobeAmericas,
      faBars,
      faUsdCircle,
      faThList,
      faDrawPolygon,
      faChartNetwork,
      faTags,
      faTasks,
      faWarehouseAlt,
      faQuestionCircle,
      faFileCheck,
      faCheck,
      faArrowToBottom,
      faSave,
      faExclamationCircle,
      faSlidersH,
      faCircle,
      faChevronRight,
      faChevronLeft,
      faPlus,
      faTrash,
      faSearch,
      faTimesCircle,
      faPen,
      faEdit,
      faPlusCircle,
      faBinoculars,
      faCopy,
      faLink,
      faCheckCircle,
      faEdit,
      faImages,
      faFileChartLine,
      faUsers,
      faCloud,
      faHourglassEnd,
      faMoneyCheckAlt,
      faUserLock,
      faKey,
      faEye,
      faSpinner,
      faCalendarDay,
      faList,
      faMinusCircle,
      faGraduationCap,
      faTruckPickup,
      faSignOutAlt
    );
  }
}
